apiVersion: v1
kind: Service
metadata:
  name: auth-api
spec:
  selector:
    app: auth-api
  ports:
    - port: 8098
      targetPort: 8098
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-api
  template:
    metadata:
      labels:
        app: auth-api
    spec:
      containers:
        - name: auth-api
          image: kharism/auth_api
          ports:
            - containerPort: 8098
          env:
            - name: MONGO_URI
              value: mongodb://mongo:27017/
          imagePullPolicy: Always
