apiVersion: v1
kind: Service
metadata:
  name: transaction_api
spec:
  selector:
    app: transaction_api
  ports:
    - port: 8099
      targetPort: 8099
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction_api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transaction_api
  template:
    metadata:
      labels:
        app: transaction_api
    spec:
      containers:
        - name: transaction_api
          image: kharism/transaction_api
          ports:
            - containerPort: 8099
          env:
            - name: MONGO_URL
              value: mongodb://mongo:27017/
          imagePullPolicy: Always
