apiVersion: v1
kind: Service
metadata:
  name: ui-api
spec:
  selector:
    app: ui-api
  ports:
    - port: 8100
      targetPort: 8100
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui-api
  template:
    metadata:
      labels:
        app: ui-api
    spec:
      containers:
        - name: ui-api
          image: kharism/ui_api
          ports:
            - containerPort: 8100
          env:
            - name: MONGO_URI
              value: mongodb://mongo:27017/
          imagePullPolicy: Always
