apiVersion: v1
kind: Service
metadata:
  name: ui_api
spec:
  selector:
    app: auth_api
  ports:
    - port: 8100
      targetPort: 8100
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui_api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui_api
  template:
    metadata:
      labels:
        app: ui_api
    spec:
      containers:
        - name: ui_api
          image: kharism/ui_api
          ports:
            - containerPort: 8100
          env:
            - name: MONGO_URL
              value: mongodb://mongo:27017/
          imagePullPolicy: Always
